# Generated by Django 4.2.17 on 2025-01-06 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0012_alter_folder_expires_at_uploadzip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 11, 4, 55, 479347, tzinfo=datetime.timezone.utc)),
        ),
    ]
