# Generated by Django 4.2.17 on 2025-01-08 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0014_alter_folder_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 23, 51, 51, 347691, tzinfo=datetime.timezone.utc)),
        ),
    ]
