# Generated by Django 4.2.17 on 2025-01-09 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0015_alter_folder_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 11, 1, 50, 87039, tzinfo=datetime.timezone.utc)),
        ),
    ]
