# Generated by Django 4.2.17 on 2025-01-09 12:11

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0016_alter_folder_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='price',
        ),
        migrations.AlterField(
            model_name='folder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 12, 11, 45, 754951, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='uploadzip',
            name='zip_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='zip_file'),
        ),
    ]
