# Generated by Django 4.2.19 on 2025-02-08 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0017_remove_folder_price_alter_folder_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 6, 5, 52, 139377, tzinfo=datetime.timezone.utc)),
        ),
    ]
